### ISSUE TITLE
Add GP optimization tutorial

### ISSUE THREAD

**Issue by catrionamurray** [lgrcia/nuance#9]
Missing link to GP opt. tutorial [here](https://nuance.readthedocs.io/en/latest/notebooks/gp.html)

**Comment by lgrcia** [comment]
Thanks @catrionamurray! 🙏🏼 You probably mean [here](https://nuance.readthedocs.io/en/latest/notebooks/multi.html#the-linear-search) and yes indeed, I plan to make a tutorial on a TESS light curve using the kernel I provide by default in nuance (otherwise you have to build your own). This is at the top of the TODO list for the docs 🔥

**Comment by lgrcia** [comment]
I think this has been [added here](https://nuance.readthedocs.io/en/latest/notebooks/tutorials/GP_optimization.html). Thanks again!
